#!/bin/bash

if [ $# -ge 1 ]
then
    echo ~
    cd $1
    mount -t proc /proc proc/
    mount --rbind /sys sys/
    mount --rbind /dev dev/
    mount --rbind /run run/
    cp /etc/resolv.conf etc/resolv.conf
    chroot $1 /bin/bash
else
    echo "One argument required"
fi

